name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: mr-analyzer/.
        push: false
        tags: webhook-api-mr-analyzer:test
        load: true
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: dbt-repo-analyzer/.
        push: false
        tags: webhook-api-dbt-analyzer:test
        load: true
    
    - name: Start container
      run: |
        docker run -d --name webhook-api-mr-analyzer -p 8080:8080 webhook-api-mr-analyzer:test
        # Wait for container to be ready
        sleep 10

    - name: Start container
      run: |
        docker run -d --name webhook-api-dbt-analyzer -p 8000:8000 webhook-api-dbt-analyzer:test
        # Wait for container to be ready
        sleep 10
    
    - name: Wait for health check
      run: |
        # Wait up to 60 seconds for the health check to be available
        timeout 60 bash -c 'until curl -f http://localhost:8080/health; do sleep 2; done'
    
    - name: Verify health check endpoint
      run: |
        # Test the health check endpoint
        response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/health)
        if [ $response -eq 200 ]; then
          echo "✅ Health check passed (HTTP $response)"
        else
          echo "❌ Health check failed (HTTP $response)"
          exit 1
        fi
    
    - name: Test health check response (optional)
      run: |
        # Optionally verify the response content
        curl -s http://localhost:8080/health | grep -q "ok\|healthy\|success" || {
          echo "❌ Health check response doesn't contain expected content"
          curl -s http://localhost:8080/health
          exit 1
        }
    
    - name: Show container logs (on failure)
      if: failure()
      run: |
        echo "Container logs:"
        docker logs webhook-api-mr-analyzer
    
    - name: Cleanup
      if: always()
      run: |
        docker stop webhook-api-mr-analyzer || true
        docker rm webhook-api-mr-analyzer || true
